trigger:
  branches:
    include:
      - release/*
    exclude:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 7.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'Build: WebAPI ' 
  inputs:
    command: build
    projects: '**/WebApi/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet publish backend --configuration $(buildConfiguration)
  name: PublishWebApi
  
  inputs:
    command: publish
    projects: '**/WebApi/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/webApi'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: dotnet publish WebGastos backend --configuration $(buildConfiguration)
  name: PublishWebApiGastos
  
  inputs:
    command: publish
    projects: '**/APIGastosDiarios/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/APIGastosDiarios'
    zipAfterPublish: true
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Suscripción de Azure 1(8bbebb30-f76b-4c12-bcc7-ea5941267e61)'
    appType: 'webApp'
    WebAppName: 'basura2024'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/webApi/*.zip'